### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by frnhr** [divio/djangocms-picture#16]

**Comment by FinalAngel** [comment]
@frnhr thanks for the report. Would you be, by any chance, able to open a pull request to add python 3 compatibility?

**Comment by mkoistinen** [comment]
@frnhr I just tried it with version 0.1.0 on Python 3.4 + Django 1.7.10 and it worked perfectly. I'm closing this for now. If you can identify some specific Python 3 issues, please open a new ticket with the versions of this plugin, Python, Django and perhaps even django CMS. Also, a stack-trace would be very useful.

**Comment by frnhr** [comment]
@mkoistinen That's cool. I was compiling a list of apps that are blocking a project from switching to Python 3, and was unsure about this app. Thanks for testing it and updating the requirements!
