### ISSUE TITLE
Width from context should be cast to integer

### ISSUE THREAD

**Issue by petrklus** [divio/djangocms-picture#32]
Hello,

As defined on some [manual pages](http://docs.django-cms.org/en/release-3.3.x/how_to/placeholders.html#templates), placeholder parameter can be defined as string instead of being an integer.

The width calculation fails in such cases and produces an error due to the context being passed without checking data type here [here](https://github.com/divio/djangocms-picture/blob/67f50bb823d7e88de62b7d53b830d7c821b50a66/djangocms_picture/cms_plugins.py#L71).

I would suggest either pre-emptively checking that the placeholder width param is an integer/float or parsing the number from string.

**Comment by petrklus** [comment]
great stuff @FinalAngel , thank you

**Comment by FinalAngel** [comment]
you are very welcome @petrklus
