### ISSUE TITLE
Make default cropping options configurable

### ISSUE THREAD

**Issue by bhrutledge** [divio/djangocms-picture#36]
At the moment, my team doesn't have much use for the thumbnailing in django-filer. It's mostly fine to ignore it, but the default cropping settings mean we'll always have to turn off "Automatic Scaling" and turn on "Use original image", to avoid artifacts of the thumbnail processors. I'm guessing I can get around this by overriding the default template, but it'd be nice if there was a configurable global default.

**Comment by FinalAngel** [comment]
We had the experience that most people are using the automatic scaling. For your case we'd have to add some settings though that might bloat the user interface. I'd recommend using the template option then or override the default template.

Introducing a setting for this also require thoughts on how to handle the other cropping settings. Any suggestion from your end?

**Comment by bhrutledge** [comment]
How about a setting like `DJANGOCMS_PICTURE_USE_ORIGINAL`, which sets `use_automatic_scaling = False` and `use_no_cropping = True`? Maybe set via [`get_changeform_initial_data`](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_changeform_initial_data)?

Or, for a more comprehensive approach (which seems excessive to me):

```python
DJANGOCMS_PICTURE_CROP_SETTINGS = {
    'use_automatic_scaling': False,
    'use_no_cropping': True,
    'use_crop': False,
    'use_upscale': False
}
```

**Comment by FinalAngel** [comment]
@divio/django-cms-core what do you think about this?

**Comment by FinalAngel** [comment]
@czpython any thoughts from your end?

**Comment by yakky** [comment]
My 2cents is that ThumbnailOption are a better place to centralize configuration than adding another setting

**Comment by bhrutledge** [comment]
@yakky Can you elaborate on how I'd use ThumbnailOption in this case?

**Comment by bhrutledge** [comment]
I don't see how ThumbnailOption would improve my situation. First, it requires a width and height, which runs counter to using the original image. Also, I don't see a way to specify a default ThumbnailOption, which means our users would have to select it under "Cropping settings", in which case they might as well change the cropping settings.

Again, since most of our images are intended to be displayed as-is, I'm trying to streamline the process for our users.

**Comment by bhrutledge** [comment]
I came up with a workaround. In a `cms_plugins.py` in my project:

```python
from cms.plugin_pool import plugin_pool
from djangocms_picture.cms_plugins import PicturePlugin as BasePicturePlugin


class PicturePlugin(BasePicturePlugin):
    """
    Override default admin for Picture plugin.

    `plugin_pool` uses `__name__` as a key, so we have to use
    the same class name as the default plugin.
    """

    def get_changeform_initial_data(self, request):
        initial = super(PicturePlugin, self).get_changeform_initial_data(request)

        initial['use_automatic_scaling'] = False
        initial['use_no_cropping'] = True

        return initial


plugin_pool.unregister_plugin(BasePicturePlugin)
plugin_pool.register_plugin(PicturePlugin)
```

**Comment by FinalAngel** [comment]
I would find this a way cleaner solution then adding additional settings. @yakky @czpython WDYT?

**Comment by yakky** [comment]
I think that working to improve ThumbnailOption is the way to go in the long run
As a workaround hacking the initial is way better than adding settings

**Comment by bhrutledge** [comment]
I'm happy with the workaround, so I'll close this out.
