### ISSUE TITLE
Plugin instance doesn't save custom attributes or with xxx settings

### ISSUE THREAD

**Issue by FabrizioA** [divio/djangocms-picture#40]
Hi,

I'm using djangocms-picture together django-filer and when I set some custom attributes (from within popup of Django CMS) it doesn't saved.
When I using the code:

                {% with 720 as width %}
                    {% placeholder "Immagine" %}
                {% endwith %}

the width attribute may be don't apply on rendered img tag.

I need to add a custom css class (class="img-responsive") on my djangocms-picture rendered image. Any suggestion?

Thank you.

**Comment by FinalAngel** [comment]
@FabrizioA thanks for the report, are you using the latest version of the plugin? If so check if the templates are up-to-date. If this is also the case, make sure "automatic scaling" is active, it only takes the value if that checkbox is active, see also: 
https://github.com/divio/djangocms-picture/blob/master/djangocms_picture/cms_plugins.py#L71

**Comment by FinalAngel** [comment]
@FabrizioA any feedback from your end? otherwise closing

**Comment by FabrizioA** [comment]
Hi @FinalAngel , sorry for my delay. I'm closing.
Thank you :)

**Comment by FinalAngel** [comment]
@FabrizioA no worries, thank you for the feedback 👍
