### ISSUE TITLE
Out put image path without <img src=""> tags

### ISSUE THREAD

**Issue by p8ul** [divio/djangocms-picture#41]
Is there a way i can Out put image path without <pre> ```< img src="">  tags.</pre>```

{% placeholder "my_image" %} 

to output => "http://locahost:8000/path/to/my_image"  ?

**Comment by FinalAngel** [comment]
@p8ul I do not understand what you would like to achieve?

**Comment by FinalAngel** [comment]
you can get the image using ``{{ instance.picture.url }}``  or ``{{ instance.external_picture }}`` if its an external picture. Checkout the models (https://github.com/divio/djangocms-picture/blob/master/djangocms_picture/models.py#L67) or template (https://github.com/divio/djangocms-picture/blob/master/djangocms_picture/templates/djangocms_picture/default/picture.html#L21)

**Comment by jerinisready** [comment]
You Can give as : 

```
{% placeholder "SliderImage" as img %}
<div class="slider__bg" style="background-image: url({{ img.url }});"></div>

```
