### ISSUE TITLE
Image align center has incorrect value

### ISSUE THREAD

**Issue by petrklus** [divio/djangocms-picture#42]
See https://github.com/divio/djangocms-picture/blob/master/djangocms_picture/models.py#L29

Align left and Align center are the same.

Temporary workaround - add following setting:

```
DJANGOCMS_PICTURE_ALIGN = (
        ('left', _('Align left')),
        ('right', _('Align right')),
        ('center', _('Align center')),
)
```

**Comment by FinalAngel** [comment]
@petrklus nice spotting, would you be able to open a PR to address the issue?
