### ISSUE TITLE
Gif Support

### ISSUE THREAD

**Issue by LordDz** [divio/djangocms-picture#56]
When I select an animated .gif image, the picture plugin accepts it but turns it into a .png image.

1.
![gif01](https://user-images.githubusercontent.com/6305945/46544137-10c00e00-c8c3-11e8-8f5b-4e8bfdd8e98f.JPG)

2.
![gif02](https://user-images.githubusercontent.com/6305945/46544140-13226800-c8c3-11e8-9ee8-2019d65358d3.JPG)

As you can see in the developer tools, it's now a png instead of a .gif

**Comment by FinalAngel** [comment]
@LordDz you would need to choose the "_Use original image_" from the **cropping settings**. Otherwise, django-filer is converting the image. This is something that would need to be improved or implemented in django-filer.

**Comment by pean45498** [comment]
Hi, how and where can I set the "Use original image" of the cropping settings?

**Comment by almasieva** [comment]
Hi, how and where can I set the "Use original image" of the cropping settings?

**Comment by fsbraun** [comment]
When double-clicking the plugin to edit, some way down the form, there is a section "Cropping settings". Open it by clicking "show".

**Comment by almasieva** [comment]
Thanks, I'v found it.
