### ISSUE TITLE
feature request: Link original image

### ISSUE THREAD

**Issue by scorpp** [divio/djangocms-picture#63]
It would be nice to bring back functionality which used to exist in now obsolete `cmsplugin-filer` - Link original image.

In short it wraps an `<img ...>` tag (which is usually a preview) with a link to original image.

This works quite well with different kinds of lightbox \ image popup scripts.

**Comment by FinalAngel** [comment]
Hello @scorpp, please add a custom template for that functionality. For this we have added that feature instead :)
