### ISSUE TITLE
SET_NULL on delete of picture

### ISSUE THREAD

**Issue by ianare** [divio/djangocms-picture#77]
I'm wondering why the foreign key is on SET_NULL if the original image is deleted?
```
picture = FilerImageField(
        verbose_name=_('Image'),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )
```

In my view it would make more sense to RESTRICT or CASCADE to avoid any unpleasant surprises on the site.

On one of our projects we removed some images in filer when doing cleanup work that wound up causing several pages on the site to have empty images. The problem is that when deleting we get no indication that the image is being used.

What do you think?

**Comment by febsn** [comment]
This is even more problematic if the responsive option is used – in this case, the page will cause a 500 error. Is there a specific reason for the `SET_NULL` option? @FinalAngel could you please shed some light? I'd be happy to contribute a PR, but I need to know the circumstances first ;-)

**Comment by FinalAngel** [comment]
@febsn I'll need to have a look again, from our testing the PR failed on certain cases (migrations fail) for existing plugins or in conjunction with djangocms-bootstrap4 (where also adaptions may be required)

**Comment by FinalAngel** [comment]
landed with https://github.com/divio/djangocms-picture/pull/84 :)
