### ISSUE TITLE
Other units for image size

### ISSUE THREAD

**Issue by m7v8** [divio/djangocms-picture#85]
The current implementation for setting width and height for an image only allows to set them in pixel.

To be more flexible (support more devices and layouts) and have more control over it should be possible to change the unit of width and height - in my case I would change it to percent.

**Comment by FinalAngel** [comment]
Hello @m7v8, thank you for your ticket.

The width and height attribute of an <img> only supports pixels:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width

This was intentionally done so in this plugin. If you'd like to use custom sizes please use the attributes field and add either classes or inline styles.

You could also add different templates that handle the width and height values (as they have no "px" suffix) and include them in the template as % or vw etc.
