### ISSUE TITLE
I'm not able to nest text inside picture

### ISSUE THREAD

**Issue by Makina14** [divio/djangocms-picture#93]
Hi everyone! This is my first post in GitHub.

I'm having troubles with this APP. I've read that in order to enable nesting in a picture, I have to add the line DJANGOCMS_PICTURE_NESTING = True in the settings.py of my project. I'm doing this and I can see the simbol + enabled when I add a picture in django cms. My problem is that when I add text for instance, I can't see it inside the picture. 

I have taken a look to the picture.html template located in djangocms_picture/templates/djangocms_picture/default and I've seen at the end of it the commented code 
{% for plugin in instance.child_plugin_instances %}
        {% render_plugin plugin %}
    {% endfor %}

When I add it in the middle of the template I can see the nested plugin getting rendered, but they don't render inside the picture. 

Could you please help me? I'm quite new to django cms and html in general.

**Comment by FinalAngel** [comment]
@Makina14 it's correct that you need to add:

```
{% for plugin in instance.child_plugin_instances %}
    {% render_plugin plugin %}
{% endfor %}
```

in the ``djangocms_picture/default.html`` template. But you can't "place it in the picture" as it's an ``<img>`` tag. You need to add it either before or after that tag. Alternatively, you could change the template to use the ``<picture>`` tag:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

But that only allows certain HTML tags to be placed inside.
