### ISSUE TITLE
Can't wrap external image in a link

### ISSUE THREAD

**Issue by bhrutledge** [divio/djangocms-picture#95]
Since v2.3.0 (specifically https://github.com/divio/djangocms-picture/pull/82), it doesn't seem possible to wrap an "External image" with a link to an "External URL" or "Internal URL". It seems that `external_picture` takes precedence over `link_url` and `link_page_id`, which means that the `<img>` gets wrapped with an `<a>` to the same image.

https://github.com/divio/djangocms-picture/blob/db9c4d49ae1b840666e5146949d536d67386e1fc/djangocms_picture/templates/djangocms_picture/default/picture.html#L3-L7

https://github.com/divio/djangocms-picture/blob/db9c4d49ae1b840666e5146949d536d67386e1fc/djangocms_picture/cms_plugins.py#L70

https://github.com/divio/djangocms-picture/blob/db9c4d49ae1b840666e5146949d536d67386e1fc/djangocms_picture/models.py#L274-L281

This is surprising behavior to me, but it's also tested:

https://github.com/divio/djangocms-picture/blob/db9c4d49ae1b840666e5146949d536d67386e1fc/tests/test_models.py#L151-L160

Is this the desired behavior? If so, could somebody explain why?

**Comment by FinalAngel** [comment]
@bhrutledge thank you very much for the report. In fact, that is not the desired result. This will be fixed in #95
